
exports.types = {
    0: 'EOC',
    1: 'Boolean',
    2: 'Integer',
    3: 'BitString',
    4: 'OctetString',
    5: 'Null',
    6: 'OID',
    7: 'ObjectDescriptor',
    8: 'External',
    9: 'Real',
   10: 'Enumeration',
   11: 'PDV',
   12: 'Utf8String',
   13: 'RelativeOID',
   16: 'Sequence',
   17: 'Set',
   18: 'NumericString',
   19: 'PrintableString',
   20: 'T61String',
   21: 'VideotexString',
   22: 'IA5String',
   23: 'UTCTime',
   24: 'GeneralizedTime',
   25: 'GraphicString',
   26: 'VisibleString',
   28: 'GeneralString',
   29: 'UniversalString',
   30: 'CharacterString',
   31: 'BMPString',
   32: 'Constructor',
  128: 'Context'
};